export interface CodeTheme {
  id: string;
  name: string;
  isDark: boolean;
  background: string;
  color: string;
  macHeaderBg: string;
  borderColor: string;
  tokenStyles: Record<string, string>;
}

export const codeThemes: CodeTheme[] = [
  {
    id: 'one-dark',
    name: 'One Dark (经典深色)',
    isDark: true,
    background: '#282c34',
    color: '#abb2bf',
    macHeaderBg: '#21252b',
    borderColor: '#1e2227',
    tokenStyles: {
      keyword: 'color: #c678dd; font-weight: 600;',
      built_in: 'color: #e6c07b;',
      type: 'color: #e6c07b;',
      literal: 'color: #56b6c2;',
      number: 'color: #d19a66;',
      operator: 'color: #56b6c2;',
      punctuation: 'color: #abb2bf;',
      string: 'color: #98c379;',
      regexp: 'color: #98c379;',
      subst: 'color: #e06c75;',
      symbol: 'color: #61afef;',
      class: 'color: #e6c07b;',
      function: 'color: #61afef;',
      title: 'color: #61afef; font-weight: 600;',
      params: 'color: #abb2bf;',
      comment: 'color: #5c6370; font-style: italic;',
      doctag: 'color: #c678dd;',
      meta: 'color: #e06c75;',
      'meta-keyword': 'color: #e06c75;',
      'meta-string': 'color: #98c379;',
      attr: 'color: #d19a66;',
      attribute: 'color: #d19a66;',
      tag: 'color: #e06c75;',
      name: 'color: #e06c75;',
      variable: 'color: #e06c75;',
    }
  },
  {
    id: 'github-light',
    name: 'GitHub (极简浅色)',
    isDark: false,
    background: '#f6f8fa',
    color: '#24292e',
    macHeaderBg: '#eaeef2',
    borderColor: '#e1e4e8',
    tokenStyles: {
      keyword: 'color: #d73a49; font-weight: 600;',
      built_in: 'color: #005cc5;',
      type: 'color: #005cc5;',
      literal: 'color: #005cc5;',
      number: 'color: #005cc5;',
      operator: 'color: #d73a49;',
      punctuation: 'color: #24292e;',
      string: 'color: #032f62;',
      regexp: 'color: #032f62;',
      subst: 'color: #24292e;',
      symbol: 'color: #005cc5;',
      class: 'color: #6f42c1;',
      function: 'color: #6f42c1;',
      title: 'color: #6f42c1; font-weight: 600;',
      params: 'color: #24292e;',
      comment: 'color: #6a737d; font-style: italic;',
      doctag: 'color: #d73a49;',
      meta: 'color: #005cc5;',
      'meta-keyword': 'color: #d73a49;',
      'meta-string': 'color: #032f62;',
      attr: 'color: #005cc5;',
      attribute: 'color: #005cc5;',
      tag: 'color: #22863a;',
      name: 'color: #22863a;',
      variable: 'color: #e36209;',
    }
  },
  {
    id: 'vs2015',
    name: 'VS Code Dark (微软深蓝)',
    isDark: true,
    background: '#1e1e1e',
    color: '#d4d4d4',
    macHeaderBg: '#252526',
    borderColor: '#333333',
    tokenStyles: {
      keyword: 'color: #569cd6; font-weight: 600;',
      built_in: 'color: #4ec9b0;',
      type: 'color: #4ec9b0;',
      literal: 'color: #569cd6;',
      number: 'color: #b5cea8;',
      operator: 'color: #d4d4d4;',
      punctuation: 'color: #d4d4d4;',
      string: 'color: #ce9178;',
      regexp: 'color: #d16969;',
      subst: 'color: #d4d4d4;',
      symbol: 'color: #4ec9b0;',
      class: 'color: #4ec9b0;',
      function: 'color: #dcdcaa;',
      title: 'color: #dcdcaa; font-weight: 600;',
      params: 'color: #9cdcfe;',
      comment: 'color: #6a9955; font-style: italic;',
      doctag: 'color: #608b4e;',
      meta: 'color: #9b9b9b;',
      'meta-keyword': 'color: #569cd6;',
      'meta-string': 'color: #ce9178;',
      attr: 'color: #9cdcfe;',
      attribute: 'color: #9cdcfe;',
      tag: 'color: #569cd6;',
      name: 'color: #569cd6;',
      variable: 'color: #9cdcfe;',
    }
  },
  {
    id: 'monokai',
    name: 'Monokai Pro (复古绚丽)',
    isDark: true,
    background: '#272822',
    color: '#f8f8f2',
    macHeaderBg: '#1e1f1c',
    borderColor: '#3e3d32',
    tokenStyles: {
      keyword: 'color: #f92672; font-weight: 600;',
      built_in: 'color: #66d9ef;',
      type: 'color: #66d9ef;',
      literal: 'color: #ae81ff;',
      number: 'color: #ae81ff;',
      operator: 'color: #f92672;',
      punctuation: 'color: #f8f8f2;',
      string: 'color: #e6db74;',
      regexp: 'color: #e6db74;',
      subst: 'color: #f8f8f2;',
      symbol: 'color: #66d9ef;',
      class: 'color: #a6e22e;',
      function: 'color: #a6e22e;',
      title: 'color: #a6e22e; font-weight: 600;',
      params: 'color: #fd971f;',
      comment: 'color: #75715e; font-style: italic;',
      doctag: 'color: #f92672;',
      meta: 'color: #75715e;',
      'meta-keyword': 'color: #f92672;',
      'meta-string': 'color: #e6db74;',
      attr: 'color: #a6e22e;',
      attribute: 'color: #a6e22e;',
      tag: 'color: #f92672;',
      name: 'color: #f92672;',
      variable: 'color: #f8f8f2;',
    }
  },
  {
    id: 'nord',
    name: 'Nord (北欧极光)',
    isDark: true,
    background: '#2e3440',
    color: '#d8dee9',
    macHeaderBg: '#242933',
    borderColor: '#3b4252',
    tokenStyles: {
      keyword: 'color: #81a1c1; font-weight: 600;',
      built_in: 'color: #8fbcbb;',
      type: 'color: #8fbcbb;',
      literal: 'color: #81a1c1;',
      number: 'color: #b48ead;',
      operator: 'color: #81a1c1;',
      punctuation: 'color: #eceff4;',
      string: 'color: #a3be8c;',
      regexp: 'color: #ebcb8b;',
      subst: 'color: #d8dee9;',
      symbol: 'color: #81a1c1;',
      class: 'color: #88c0d0;',
      function: 'color: #88c0d0;',
      title: 'color: #88c0d0; font-weight: 600;',
      params: 'color: #e5e9f0;',
      comment: 'color: #616e88; font-style: italic;',
      doctag: 'color: #81a1c1;',
      meta: 'color: #5e81ac;',
      'meta-keyword': 'color: #81a1c1;',
      'meta-string': 'color: #a3be8c;',
      attr: 'color: #8fbcbb;',
      attribute: 'color: #8fbcbb;',
      tag: 'color: #81a1c1;',
      name: 'color: #81a1c1;',
      variable: 'color: #d8dee9;',
    }
  },
  {
    id: 'night-owl',
    name: 'Night Owl (夜猫深青)',
    isDark: true,
    background: '#011627',
    color: '#d6deeb',
    macHeaderBg: '#010e1a',
    borderColor: '#0b2942',
    tokenStyles: {
      keyword: 'color: #c792ea; font-weight: 600;',
      built_in: 'color: #addb67;',
      type: 'color: #addb67;',
      literal: 'color: #ff5874;',
      number: 'color: #f78c6c;',
      operator: 'color: #c792ea;',
      punctuation: 'color: #d6deeb;',
      string: 'color: #ecc48d;',
      regexp: 'color: #5ca7e4;',
      subst: 'color: #d6deeb;',
      symbol: 'color: #addb67;',
      class: 'color: #ffcb8b;',
      function: 'color: #82aaff;',
      title: 'color: #82aaff; font-weight: 600;',
      params: 'color: #d7dbe0;',
      comment: 'color: #637777; font-style: italic;',
      doctag: 'color: #c792ea;',
      meta: 'color: #7fdbca;',
      'meta-keyword': 'color: #c792ea;',
      'meta-string': 'color: #ecc48d;',
      attr: 'color: #7fdbca;',
      attribute: 'color: #7fdbca;',
      tag: 'color: #7fdbca;',
      name: 'color: #7fdbca;',
      variable: 'color: #d6deeb;',
    }
  },
  {
    id: 'xcode',
    name: 'Xcode (苹果浅色)',
    isDark: false,
    background: '#ffffff',
    color: '#000000',
    macHeaderBg: '#f0f0f0',
    borderColor: '#e5e5e5',
    tokenStyles: {
      keyword: 'color: #ad3da4; font-weight: 600;',
      built_in: 'color: #703daa;',
      type: 'color: #703daa;',
      literal: 'color: #272ad8;',
      number: 'color: #272ad8;',
      operator: 'color: #262626;',
      punctuation: 'color: #000000;',
      string: 'color: #d12f1b;',
      regexp: 'color: #0e0eff;',
      subst: 'color: #000000;',
      symbol: 'color: #703daa;',
      class: 'color: #3e8087;',
      function: 'color: #4b21b0;',
      title: 'color: #4b21b0; font-weight: 600;',
      params: 'color: #000000;',
      comment: 'color: #65798c; font-style: italic;',
      doctag: 'color: #ad3da4;',
      meta: 'color: #643820;',
      'meta-keyword': 'color: #ad3da4;',
      'meta-string': 'color: #d12f1b;',
      attr: 'color: #836c28;',
      attribute: 'color: #836c28;',
      tag: 'color: #ad3da4;',
      name: 'color: #ad3da4;',
      variable: 'color: #000000;',
    }
  }
];

export const getCodeTheme = (id: string): CodeTheme => {
  return codeThemes.find(t => t.id === id) || codeThemes[0];
};
